/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 磁盘信息结构体，包含总空间和可用空间信息 */
export interface DiskInfo {
  /** 总空间（字节） */
  totalBytes: number
  /** 可用空间（字节） */
  availableBytes: number
}

/**
 * 获取 Windows 系统主磁盘（C 盘）的空间信息
 *
 * # 返回值
 *
 * 返回包含总空间和可用空间的 DiskInfo 结构体
 */
export declare function getMainDiskInfo(): DiskInfo

/**
 * 将输入数字加上 100 并返回结果
 *
 * # 参数
 *
 * * `input` - 要加 100 的数字
 *
 * # 返回值
 *
 * 返回输入数字加 100 的结果
 */
export declare function plus100(input: number): number
