/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getMainDiskInfo(): PackageJson

export interface PackageJson {
  totalBytes: number
  availableBytes: number
}

export declare function plus100(input: number): number
